server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/GraduationProject?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.163.com
    port: 465
    username: wy03104@163.com
#    username: ${MAIL_USERNAME}
#    password: ${MAIL_PASSWORD}
    password: QFNQBTSSLJFKQLFB
    properties:
      from: wy03104@163.com
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          auth: true
          starttls:
            enable: true
    protocol: smtp
  data:
    redis:
      host: 127.0.0.1
      port: 6379
#      password: 1234
      timeout: 20000

logging:
  level:
    org.springframework.data.redis: DEBUG
    io.lettuce: DEBUG
    org:
      springframework:
        web: DEBUG
        security: DEBUG
# springdoc
springdoc:
  swagger-ui:
    path: /doc-ui
  api-docs:
    path: /api-docs

# openAPI
api:
  title: demo demo
  version: 1.0.0
  description: demo demo

jwt:
  secret: ${JWT_SECRET:your-secret-key}
  expiration: 2073600000 # 24 days
#  expiration: 86400000 # 24 hours

